/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as CopyrightPolicyRouteImport } from './routes/copyright-policy'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SearchWebRouteImport } from './routes/search-web'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryPartIdRouteImport } from './routes/library.$partId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightPolicyRoute = CopyrightPolicyRouteImport.update({
  id: '/copyright-policy',
  path: '/copyright-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchWebRoute = SearchWebRouteImport.update({
  id: '/search-web',
  path: '/search-web',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPartIdRoute = LibraryPartIdRouteImport.update({
  id: '/library/$partId',
  path: '/library/$partId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/requests': typeof RequestsRoute
  '/search-web': typeof SearchWebRoute
  '/upload': typeof UploadRoute
  '/library/$partId': typeof LibraryPartIdRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/requests': typeof RequestsRoute
  '/search-web': typeof SearchWebRoute
  '/upload': typeof UploadRoute
  '/library/$partId': typeof LibraryPartIdRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/copyright-policy': typeof CopyrightPolicyRoute
  '/requests': typeof RequestsRoute
  '/search-web': typeof SearchWebRoute
  '/upload': typeof UploadRoute
  '/library/$partId': typeof LibraryPartIdRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/copyright-policy'
    | '/requests'
    | '/search-web'
    | '/upload'
    | '/library/$partId'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/copyright-policy'
    | '/requests'
    | '/search-web'
    | '/upload'
    | '/library/$partId'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/community-guidelines'
    | '/copyright-policy'
    | '/requests'
    | '/search-web'
    | '/upload'
    | '/library/$partId'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CopyrightPolicyRoute: typeof CopyrightPolicyRoute
  RequestsRoute: typeof RequestsRoute
  SearchWebRoute: typeof SearchWebRoute
  UploadRoute: typeof UploadRoute
  LibraryPartIdRoute: typeof LibraryPartIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-policy': {
      id: '/copyright-policy'
      path: '/copyright-policy'
      fullPath: '/copyright-policy'
      preLoaderRoute: typeof CopyrightPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-web': {
      id: '/search-web'
      path: '/search-web'
      fullPath: '/search-web'
      preLoaderRoute: typeof SearchWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$partId': {
      id: '/library/$partId'
      path: '/library/$partId'
      fullPath: '/library/$partId'
      preLoaderRoute: typeof LibraryPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CopyrightPolicyRoute: CopyrightPolicyRoute,
  RequestsRoute: RequestsRoute,
  SearchWebRoute: SearchWebRoute,
  UploadRoute: UploadRoute,
  LibraryPartIdRoute: LibraryPartIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
